version: '2'
services:
    service01:
        container_name: service01-server
        build:
            context: spring-boot-service01
            dockerfile: Dockerfile
        image: spring-boot-service01:latest
        ports:
            - 8081:8080
        networks:
            - composite-service-network
    service02:
        container_name: service02-server
        build:
            context: spring-boot-service02
            dockerfile: Dockerfile
        image: spring-boot-service02:latest
        ports:
            - 8082:8080
        networks:
            - composite-service-network
networks:
    composite-service-network:
        driver: bridge