server:
  port: 8081

spring:
  cloud:
    function:
      definition: sendTransactionEvent
    stream:
      output-bindings:
        sendTransfer-out-0
      bindings:
        sendTransactionEvent-out-0:
          destination: financial-transactions
        sendTransfer-out-0:
          destination: financial-transactions

      kafka:
        binder:
          brokers: localhost:9094

  integration:
    poller:
      fixed-delay: 60000

